#!/usr/bin/env python3
"""
gen_random_weights.py — Generate random-init weights.h WITHOUT PyTorch.

Uses only Python stdlib + numpy (pip install numpy).
Output is NOT a trained model — text will still be garbage.
Use this only to test that the firmware pipeline works before training.

Usage:
  pip3 install numpy
  python3 tools/gen_random_weights.py
  idf.py build && idf.py flash monitor
"""

import struct, random, math
from pathlib import Path

# ── Must match tinyllm.h ──────────────────────────────────────────────────────
VOCAB   = 95
EMBD    = 64
HEADS   = 4
LAYERS  = 2
FF      = EMBD * 4   # 256

OUTPUT  = Path(__file__).parent.parent / "components" / "tinyllm" / "include" / "weights.h"

random.seed(42)

def randn(n, std=0.02):
    """Box-Muller Gaussian samples, no numpy needed."""
    out = []
    for _ in range(0, n, 2):
        u1 = random.random() or 1e-10
        u2 = random.random()
        z0 = math.sqrt(-2 * math.log(u1)) * math.cos(2 * math.pi * u2)
        z1 = math.sqrt(-2 * math.log(u1)) * math.sin(2 * math.pi * u2)
        out.extend([z0 * std, z1 * std])
    return out[:n]

def quantize(weights):
    """Symmetric per-tensor INT8. Returns (int8_list, scale_float)."""
    abs_max = max(abs(w) for w in weights) or 1e-6
    scale   = abs_max / 127.0
    q       = [max(-127, min(127, round(w / scale))) for w in weights]
    return q, scale

def int8_array(name, weights, comment=""):
    q, scale = quantize(weights)
    vals = ", ".join(str(v) for v in q)
    cmt  = f"  /* {comment} */" if comment else ""
    return f"const int8_t {name}[{len(q)}] = {{{vals}}};{cmt}\n", scale

def float_array(name, values, comment=""):
    vals = ", ".join(f"{v:.8f}f" for v in values)
    cmt  = f"  /* {comment} */" if comment else ""
    return f"const float {name}[{len(values)}] = {{{values[0]:.8f}f{', '.join(f'{v:.8f}f' for v in values[1:])}}};{cmt}\n"

lines = [
    "/* AUTO-GENERATED by tools/gen_random_weights.py — random init, NOT trained */\n",
    "#pragma once\n",
    '#include <stdint.h>\n',
    '#include "tinyllm.h"\n\n',
    "#define _V TINYLLM_VOCAB_SIZE\n",
    "#define _E TINYLLM_N_EMBD\n",
    "#define _L TINYLLM_N_LAYER\n",
    "#define _F TINYLLM_FF_DIM\n\n",
]

# Token embedding  [V × E]
emb_w = randn(VOCAB * EMBD, std=0.02)
body, emb_scale = quantize(emb_w)
vals = ", ".join(str(v) for v in body)
lines.append(f"const int8_t g_token_emb[_V * _E] = {{{vals}}};\n")
lines.append(f"const float  g_token_emb_scale = {emb_scale:.8f}f;\n")
lines.append(f"const float  g_lm_head_scale   = {emb_scale:.8f}f;\n\n")

# RMSNorm weights (ones → identity)
ones = [1.0] * EMBD
for arr_name in ("g_ln1_weight", "g_ln2_weight"):
    rows = []
    for l in range(LAYERS):
        vals = ", ".join(f"1.00000000f" for _ in range(EMBD))
        rows.append(f"    /* layer {l} */ {{{vals}}}")
    lines.append(f"const float {arr_name}[_L][_E] = {{\n" + ",\n".join(rows) + "\n};\n\n")

# Per-layer weight matrices
def layer_int8_block(var_name, rows_per_layer, cols, std=0.02):
    out = [f"const int8_t {var_name}[_L][{rows_per_layer} * {cols}] = {{\n"]
    scales = []
    for l in range(LAYERS):
        w = randn(rows_per_layer * cols, std)
        q, sc = quantize(w)
        scales.append(sc)
        out.append(f"    /* layer {l} */ {{{', '.join(str(v) for v in q)}}},\n")
    out.append("};\n")
    return "".join(out), scales

# Attention QKV  [L][3E × E]
body, scales = layer_int8_block("g_attn_qkv_weight", 3 * EMBD, EMBD)
lines.append(body)
lines.append(f"const float g_attn_qkv_scale[_L] = {{{', '.join(f'{s:.8f}f' for s in scales)}}};\n\n")

# Attention proj  [L][E × E]
body, scales = layer_int8_block("g_attn_proj_weight", EMBD, EMBD)
lines.append(body)
lines.append(f"const float g_attn_proj_scale[_L] = {{{', '.join(f'{s:.8f}f' for s in scales)}}};\n\n")

# FFN fc  [L][F × E]
body, scales = layer_int8_block("g_ffn_fc_weight", FF, EMBD)
lines.append(body)
lines.append(f"const float g_ffn_fc_scale[_L] = {{{', '.join(f'{s:.8f}f' for s in scales)}}};\n\n")

# FFN proj  [L][E × F]
body, scales = layer_int8_block("g_ffn_proj_weight", EMBD, FF)
lines.append(body)
lines.append(f"const float g_ffn_proj_scale[_L] = {{{', '.join(f'{s:.8f}f' for s in scales)}}};\n\n")

# Final RMSNorm
lines.append(f"const float g_ln_f_weight[_E] = {{{', '.join('1.00000000f' for _ in range(EMBD))}}};\n")

OUTPUT.parent.mkdir(parents=True, exist_ok=True)
OUTPUT.write_text("".join(lines))

total_int8 = VOCAB*EMBD + LAYERS*(3*EMBD*EMBD + EMBD*EMBD + FF*EMBD + EMBD*FF)
print(f"Written: {OUTPUT}")
print(f"INT8 weight bytes: {total_int8:,} ({total_int8//1024} KB)")
print()
print("NOTE: This is random init — text output will still be nonsense.")
print("Run tools/train_tinyllm.py (needs PyTorch) for real text generation.")

